In [1]:
import numpy as np

In [3]:
a = np.arange(11,15)

In [4]:
a

array([11, 12, 13, 14])

In [18]:
a[a>12]

array([13, 14])

In [11]:
ar = [1,2,3,4,5,6]

In [22]:
typeof?

Object `typeof` not found.


In [23]:
type?

Init signature: type(self, /, *args, **kwargs)
Docstring:     
type(object_or_name, bases, dict)
type(object) -> the object's type
type(name, bases, dict) -> a new type
Type:           type


In [24]:
type(a)

numpy.ndarray

In [25]:
type(ar)

list

In [26]:
ar =np.array(ar)

In [27]:
type(ar)

numpy.ndarray

In [28]:
ar

array([1, 2, 3, 4, 5, 6])

In [30]:
ar[ar<3]

array([1, 2])

In [33]:
b = np.array([True,False,True,False])

In [40]:
a[np.array([1,3])]#this is for pulling the indices 1 and 3 from array a

array([12, 14])

In [ ]:
idx = np.array([1,3],[2,3])

In [45]:
np.min(a)

11