In [1]:
import numpy as np

In [38]:
x = np.array([1,2,3])

In [18]:
y=np.array([4,5,6])

In [39]:
z= np.hstack([x,y])

In [50]:
z

array([1, 2, 3, 4, 5, 6])

In [47]:
lower , upper = np.hsplit(z,[5])

In [48]:
lower

array([1, 2, 3, 4, 5])

In [49]:
upper

array([6])

In [51]:
a=np.arange(5)

In [52]:
a

array([0, 1, 2, 3, 4])

In [53]:
a.shape

(5,)

In [55]:
a =np.vstack(a)

In [56]:
a.shape

(5, 1)

In [60]:
b =np.array([1,2,3,4,5])

In [61]:
print('b is =>', -b)

b is => [-1 -2 -3 -4 -5]


In [62]:
np.abs(b)

array([1, 2, 3, 4, 5])