In [1]:
import numpy as np

In [6]:
x = np.ones([10],dtype='int32')

In [7]:
x

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [5]:
x.dtype

dtype('float64')

In [10]:
x5 = np.full(10,5)

In [11]:
x5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [20]:
x2=np.arange(0,50,2)

In [21]:
x2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [17]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use ``linspace`` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distan