In [35]:
import numpy as np

In [9]:
x =np.arange(9).reshape(3,3)

In [10]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
x[:,2]

array([2, 5, 8])

In [2]:
total = 0
for i in range(10):
    total+=i

In [3]:
total

45

In [4]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
L2 = [str(c) for c in L]
type(L2[0])

str

In [17]:
L3=np.array([1,2,3,4,False],dtype='float32')
L3

array([1., 2., 3., 4., 0.], dtype=float32)

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.full((3,2),3.14)

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

In [43]:
np.random.randint(0,10,(3,3))

array([[6, 0, 3],
       [2, 5, 1],
       [0, 9, 9]])

In [48]:
np.eye(1)

array([[1.]])

In [53]:
np.random.seed(0)     #seeding so as ensure same the number generated each time the code is run
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10, size=(3,5,5))

print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]
  [0 1 9 9 0]]

 [[4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]
  [4 9 8 1 1]
  [7 9 9 3 6]]

 [[7 2 0 3 5]
  [9 4 4 6 4]
  [4 3 4 4 8]
  [4 3 7 5 5]
  [0 1 5 9 3]]]


In [66]:
print('dimensions:',format(np.ndim(x2)))

dimensions: 2


In [71]:
print("type is ",x3.dtype)

type is  int64


In [72]:
#accessing single elements

In [74]:
x1

array([5, 0, 3, 3, 7, 9])

In [75]:
x1[-1]

9

In [76]:
#accessing multidimensional arrays

In [77]:
x = np.arange(10)

In [78]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [81]:
x[5:]

array([5, 6, 7, 8, 9])

In [83]:
x[::-1]   #when the step is negative the start and stop are swapped. this becomes a means of reversing the arrau

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [84]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]
  [0 1 9 9 0]]

 [[4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]
  [4 9 8 1 1]
  [7 9 9 3 6]]

 [[7 2 0 3 5]
  [9 4 4 6 4]
  [4 3 4 4 8]
  [4 3 7 5 5]
  [0 1 5 9 3]]]


In [97]:
x3[0,:2]

array([[8, 1, 5, 9, 8],
       [9, 4, 3, 0, 3]])

In [101]:
#  x [ block, row , col]

In [109]:
x3[0,:,1]

array([1, 4, 0, 3, 1])

In [110]:
#two dimensional slicing

In [111]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [112]:
x2[0,:]

array([3, 5, 2, 4])

In [113]:
x2[:,1]    #[rows , cols] ->all the rows and col number

array([5, 6, 6])

In [114]:
x2[:,-1]   #negative index will give the last column


array([4, 8, 7])

In [115]:
#subarrays

In [116]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [125]:
x2_sub = x2[:2,:2]

In [126]:
x2_sub

array([[3, 5],
       [7, 6]])

In [127]:
x2_sub[0,0]=99


In [128]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [129]:
#creating copies of arrays

In [130]:
x2_copy = x2[:2,:2].copy()

In [131]:
x2_copy

array([[99,  5],
       [ 7,  6]])

In [134]:
x2_copy[0,1] =99

In [136]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [137]:
#concactinating arrays

In [142]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.vstack([x,y])

In [143]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7],
        [0, 1, 9, 9, 0]],

       [[4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1],
        [4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6]],

       [[7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4],
        [4, 3, 4, 4, 8],
        [4, 3, 7, 5, 5],
        [0, 1, 5, 9, 3]]])

In [145]:
x3[0]

array([[8, 1, 5, 9, 8],
       [9, 4, 3, 0, 3],
       [5, 0, 2, 3, 8],
       [1, 3, 3, 3, 7],
       [0, 1, 9, 9, 0]])

In [146]:
x3[0,0]

array([8, 1, 5, 9, 8])

In [149]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [153]:
y = np.array([[99],[99],[99]])
y

array([[99],
       [99],
       [99]])

In [154]:
np.hstack([x2,y])

array([[99,  5,  2,  4, 99],
       [ 7,  6,  8,  8, 99],
       [ 1,  6,  7,  7, 99]])

In [158]:
x= np.arange(10)

In [159]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
x_1 , x_2, x_3 = np.split(x,[3,5])

In [161]:
x_1

array([0, 1, 2])

In [163]:
grid = np.arange(16).reshape((4,4))

In [164]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [165]:
np.hsplit(grid,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [166]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
np.add(x,100)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [170]:
(x+100)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [171]:
x= [-1,-3,-3,-5,-6]

In [174]:
np.absolute(x)

array([1, 3, 3, 5, 6])