In [39]:
import numpy as np

In [62]:

np.random.seed(0)

In [64]:
x =np.random.randint(10, size =6)
x

In [82]:
xy = np.arange(10)

In [ ]:
xy = np.arange

In [80]:
xy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
x2 =np.random.randint(10, size=(10,5))

In [104]:
x2.dtype

dtype('int64')

In [105]:
x2.shape

(10, 5)

In [112]:
x3=np.random.randint(10,size=(3,5,5))

In [113]:
x3

array([[[0, 4, 9, 0, 6],
        [4, 2, 4, 6, 3],
        [3, 7, 8, 5, 0],
        [8, 5, 4, 7, 4],
        [1, 3, 3, 9, 2]],

       [[5, 2, 3, 5, 7],
        [2, 7, 1, 6, 5],
        [0, 0, 3, 1, 9],
        [9, 6, 6, 7, 8],
        [8, 7, 0, 8, 6]],

       [[8, 9, 8, 3, 6],
        [1, 7, 4, 9, 2],
        [0, 8, 2, 7, 8],
        [4, 4, 1, 7, 6],
        [9, 4, 1, 5, 9]]])

In [117]:
x3[0,:,0]

array([0, 4, 3, 8, 1])

In [118]:
x4 =x2

In [119]:
x4

array([[8, 3, 8, 2, 8],
       [4, 3, 0, 4, 3],
       [6, 9, 8, 0, 8],
       [5, 9, 0, 9, 6],
       [5, 3, 1, 8, 0],
       [4, 9, 6, 5, 7],
       [8, 8, 9, 2, 8],
       [6, 6, 9, 1, 6],
       [8, 8, 3, 2, 3],
       [6, 3, 6, 5, 7]])

In [120]:
for i in range(2):
    x4[0,i] =100

In [121]:
x4

array([[100, 100,   8,   2,   8],
       [  4,   3,   0,   4,   3],
       [  6,   9,   8,   0,   8],
       [  5,   9,   0,   9,   6],
       [  5,   3,   1,   8,   0],
       [  4,   9,   6,   5,   7],
       [  8,   8,   9,   2,   8],
       [  6,   6,   9,   1,   6],
       [  8,   8,   3,   2,   3],
       [  6,   3,   6,   5,   7]])

In [122]:
x2

array([[100, 100,   8,   2,   8],
       [  4,   3,   0,   4,   3],
       [  6,   9,   8,   0,   8],
       [  5,   9,   0,   9,   6],
       [  5,   3,   1,   8,   0],
       [  4,   9,   6,   5,   7],
       [  8,   8,   9,   2,   8],
       [  6,   6,   9,   1,   6],
       [  8,   8,   3,   2,   3],
       [  6,   3,   6,   5,   7]])

In [125]:
grid = np.arange(1,10)

In [126]:
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
x =np.array([1,2,3])

In [ ]:
x =np.array

In [129]:
x

array([1, 3, 4])

In [134]:
y =[4,5,6]

In [136]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [138]:
grid =[[1,2,4],[5,6,7]]

In [142]:
np.concatenate([grid,grid])

array([[1, 2, 4],
       [5, 6, 7],
       [1, 2, 4],
       [5, 6, 7]])